/* auto-generated by NAPI-RS */
/* eslint-disable */
/** NAPI 句柄：包装 [`CheckpointStore`]，向 TS 侧暴露 create/restore/list/diff。 */
export declare class CheckpointStoreHandle {
  /** 是否在 reflink-capable 文件系统上（btrfs/apfs 等）。 */
  get reflinkCapable(): boolean
  /** 工作区根目录。 */
  get cwd(): string
  /** store 目录的绝对路径。 */
  get storeDir(): string
  /** 当前缓存中的 checkpoint 数量。 */
  get len(): Promise<number>
  /**
   * 创建一个 checkpoint：捕获 `paths` 的当前快照。
   *
   * - `prompt_index`：prompt 索引（0-based，单调递增）
   * - `label`：用户可读标签
   * - `paths`：要捕获的文件路径（相对 cwd 或绝对）
   */
  create(promptIndex: number, label: string, paths: Array<string>): Promise<number>
  /** 回滚到指定 checkpoint。 */
  restore(promptId: number): Promise<RestoreResultDto>
  /** 列出所有 checkpoint 的元数据（按 id 升序）。 */
  list(): Promise<Array<CheckpointMetaDto>>
  /** 计算两个 checkpoint 之间的文件差异。 */
  diff(fromId: number, toId: number): Promise<DiffResultDto>
  /** 删除 `>= target` 的所有 checkpoint。 */
  truncateFrom(target: number): Promise<void>
  /** 更新驱逐策略配置。 */
  updatePolicy(maxCheckpoints?: number | undefined | null, maxSizeMb?: number | undefined | null, swapPolicy?: string | undefined | null): Promise<void>
}

/** Checkpoint 元数据（TS 侧）。 */
export interface CheckpointMetaDto {
  id: number
  label: string
  createdAt: string
  numFiles: number
  sizeBytes: number
}

/** Checkpoint store 创建选项。 */
export interface CheckpointStoreOptions {
  /** 工作区根目录（cwd）。 */
  cwd: string
  /** Session ID（用于隔离不同 session 的 checkpoint）。 */
  sessionId: string
  /** 最大保留 checkpoint 数量（默认 64）。 */
  maxCheckpoints?: number
  /** 最大总字节数（MB，默认 256）。 */
  maxSizeMb?: number
  /** 驱逐策略（"lru" | "lru-size" | "fifo" | "none"，默认 "lru"）。 */
  swapPolicy?: string
}

/** 创建一个 checkpoint store 句柄。 */
export declare function createCheckpointStore(opts: CheckpointStoreOptions): CheckpointStoreHandle

/** diff 操作的结果（TS 侧）。 */
export interface DiffResultDto {
  added: Array<string>
  modified: Array<string>
  removed: Array<string>
}

/** 单个文件的 rewind 冲突（TS 侧）。 */
export interface FileRewindConflictDto {
  path: string
  conflictType: string
}

/** restore 操作的结果（TS 侧）。 */
export interface RestoreResultDto {
  success: boolean
  targetPromptIndex: number
  revertedFiles: Array<string>
  cleanFiles: Array<string>
  conflicts: Array<FileRewindConflictDto>
  error?: string
}
