import { createRequire } from "node:module";
import * as path from "node:path";

/**
 * Nexus Sandbox native addon loader.
 *
 * Loads the platform-specific `nexus_sandbox.<platform>-<arch>.node` binary
 * generated by `napi build`. Mirrors the loader pattern from
 * `@oh-my-pi/pi-natives` but stripped down to the essentials — no version
 * sentinel, no embedded-addon extraction, no Windows staging cache.
 *
 * On platforms where the Landlock/Seatbelt backend is unavailable (e.g.
 * Windows fallback to ISO FS), the native addon still loads; the platform
 * gating happens inside the Rust crate via `cfg(target_os)`.
 */

const SUPPORTED_PLATFORMS = [
	"linux-x64",
	"linux-arm64",
	"darwin-x64",
	"darwin-arm64",
	"win32-x64",
];

function loadNative() {
	const platformTag = `${process.platform}-${process.arch}`;
	if (!SUPPORTED_PLATFORMS.includes(platformTag)) {
		throw new Error(
			`Unsupported platform: ${platformTag}\n` +
				`Supported platforms: ${SUPPORTED_PLATFORMS.join(", ")}`,
		);
	}

	const filename = `nexus-sandbox.${platformTag}.node`;
	const require_ = createRequire(import.meta.url);
	const nativeDir = path.join(import.meta.dir);

	const candidates = [
		path.join(nativeDir, filename),
		path.join(nativeDir, "..", "build", "Release", filename),
		path.join(nativeDir, "..", "build", "Debug", filename),
	];

	const errors = [];
	for (const candidate of candidates) {
		try {
			return require_(candidate);
		} catch (err) {
			const message = err instanceof Error ? err.message : String(err);
			errors.push(`${candidate}: ${message}`);
		}
	}

	const details = errors.map((error) => `- ${error}`).join("\n");
	throw new Error(
		`Failed to load nexus-sandbox native addon for ${platformTag}.\n\n` +
			`Tried:\n${details}\n\n` +
			"If developing locally, build with: bun --cwd=packages/nexus-sandbox run build",
	);
}

const nativeBindings = loadNative();

export const createSandbox = nativeBindings.createSandbox;
export const SandboxHandle = nativeBindings.SandboxHandle;
